repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format --force-exclude
        language: system
        types: [python]
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check --fix --force-exclude
        language: system
        types: [python]
      - id: biome
        name: biome
        entry:
          npx biome check --write --no-errors-on-unmatched
          --files-ignore-unknown=true
        language: system
        types_or: [javascript, json, css]
      - id: prettier
        name: prettier
        entry: npx prettier --write --ignore-unknown
        language: system
        types_or: [markdown, yaml, html]
