# Generated by Django 5.2.16 on 2026-07-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BuildRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "command",
                    models.CharField(
                        choices=[
                            ("build_schedule", "Schedule"),
                            ("build_actuals", "Actuals"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("service_date", models.DateField()),
                ("source_version", models.CharField(blank=True, max_length=128)),
                ("artifact_path", models.CharField(blank=True, max_length=512)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["command", "service_date", "status"],
                        name="pipeline_bu_command_a2351e_idx",
                    )
                ],
            },
        ),
    ]
